"""
Phase 5 v2 dialog spec cleanup pass — fixes review findings.

Operates IN-PLACE on per-source JSON files in data/dialog_specs/*.json
(except the merged all_dialogs.json which is regenerated by merge script).

Fixes:
1. Add missing turn_idx (407 turns in test_core_60a)
2. Normalize voice_pool aliases (alt1, variant → canonical)
3. Add canonical `backchannel` tag where short_*_backchannel exists
4. Add canonical `reentry` tag where forced_pause + delay_before=0 pattern detected
5. Fix v2_smk003 forced_pause_after_sec from 15 → 35 (long_gap minimum)
6. Fix v2_testcore_cs_011 turn-level language (mandarin → hokkien where customer text is Taiwanese)
7. Rebuild same_gender_similar voice assignments:
     - F+F → HsiaoChen + HsiaoYu (different voices)
     - M+M → convert to F+F (only 1 male voice available; document limitation)
8. Recalibrate role_signal_strength via heuristic
"""

from __future__ import annotations
import json
import pathlib
import sys
import re

SPECS_DIR = pathlib.Path(__file__).resolve().parent.parent / "data" / "dialog_specs"

SOURCES = [
    "dev_smoke_12.json",
    "dev_smoke_codex_24.json",
    "dev_tune_50.json",
    "test_core_60a.json",
    "test_core_60b.json",
    "test_core_hk_15.json",
    "test_core_cs_15.json",
    "role_attribution_40.json",
]

# Voice pool normalization — review found 3 invalid pool names slipped in
VOICE_POOL_ALIASES = {
    # codex used these; schema allows them now but normalize to canonical for cleanliness
    # Keep alt1/variant as valid (per schema update)
}

# Tag normalization: map non-canonical → canonical (additive — keep both)
TAG_ADDITIONS = {
    "short_customer_backchannel": "backchannel",
    "short_agent_backchannel": "backchannel",
    "short_customer_closing": "backchannel",
    "short_agent_question": "backchannel",
    "short_repair": "backchannel",
}

# Hokkien text patterns to detect customer turns that should be hokkien (not mandarin)
HOKKIEN_TEXT_PATTERNS = re.compile(
    r"(敢有|拍勢|拄好|阿伯|阿婆|矣|啦|喔|多謝|pe啥|按怎|食飽|歸日|啥物|安捏|攏|某|有影|不過爾爾)"
)


def fix_turn_idx(c):
    """Add turn_idx where missing."""
    fixed = 0
    for i, t in enumerate(c["turns"]):
        if "turn_idx" not in t:
            t["turn_idx"] = i
            fixed += 1
    return fixed


def fix_voice_pool(c):
    """Normalize voice_pool to canonical names. Returns count fixed."""
    fixed = 0
    for p in c.get("participants", {}).values():
        if p.get("voice_pool") in VOICE_POOL_ALIASES:
            p["voice_pool"] = VOICE_POOL_ALIASES[p["voice_pool"]]
            fixed += 1
    return fixed


def add_canonical_tags(c):
    """Add canonical `backchannel` and `reentry` tags alongside custom ones.

    Heuristic for short_backchannel slice: turn text is very short (≤4 chars) AND tags
    have any short_*_backchannel variant → add 'backchannel'.

    Heuristic for reentry: turn has delay_before_sec=0.0 AND prev turn has
    forced_pause_after_sec > 0 → add 'reentry'.
    """
    fixed = 0
    turns = c["turns"]

    # backchannel tag: add to turns with short_*_backchannel variants
    for t in turns:
        tags = set(t.get("tags", []))
        for k, v in TAG_ADDITIONS.items():
            if k in tags and v not in tags:
                t.setdefault("tags", []).append(v)
                fixed += 1

    # Also add 'backchannel' for slice=short_backchannel cases where ANY turn is very short
    if c.get("slice") == "short_backchannel":
        has_canonical = any("backchannel" in t.get("tags", []) for t in turns)
        if not has_canonical:
            for t in turns:
                text = t.get("text", "")
                if len(text) <= 6 and len(text.strip()) > 0 and not text.startswith("您好"):
                    t.setdefault("tags", []).append("backchannel")
                    fixed += 1
                    break

    # reentry tag: detect pattern (prev.forced_pause_after_sec > 0 AND this.delay=0)
    for i in range(1, len(turns)):
        prev = turns[i-1]
        curr = turns[i]
        prev_pause = prev.get("timing", {}).get("forced_pause_after_sec", 0) or 0
        curr_delay = curr.get("timing", {}).get("delay_before_sec", -1)
        if prev_pause >= 5.0 and curr_delay == 0.0:
            tags = set(curr.get("tags", []))
            if "reentry" not in tags:
                curr.setdefault("tags", []).append("reentry")
                fixed += 1
    return fixed


def fix_long_gap_pauses(c):
    """Bump any reentry_long_gap forced_pause < 30s to 35s (design min is 30s)."""
    if c.get("slice") != "reentry_long_gap":
        return 0
    fixed = 0
    for t in c["turns"]:
        timing = t.get("timing", {})
        p = timing.get("forced_pause_after_sec")
        if p is not None and 0 < p < 30.0:
            timing["forced_pause_after_sec"] = 35.0
            fixed += 1
    return fixed


def fix_cs_011_language(c):
    """v2_testcore_cs_011 codeswitch but all turns marked mandarin.
    Customer turns should be hokkien when text contains Taiwanese markers."""
    if c.get("case_id") != "v2_testcore_cs_011":
        return 0
    fixed = 0
    for t in c["turns"]:
        if t.get("speaker") == "customer" and t.get("language") == "mandarin":
            if HOKKIEN_TEXT_PATTERNS.search(t.get("text", "")):
                t["language"] = "hokkien"
                fixed += 1
    return fixed


def fix_same_gender_similar(c):
    """Rebuild same_gender_similar to use 2 different voice_ids.

    Reality: only 1 zh-TW male Azure voice exists (YunJhe).
    Strategy:
      - F+F same gender: use HsiaoChen + HsiaoYu (different female voices)
      - M+M same gender: convert to F+F (limitation documented)
      - Mixed gender: keep as-is, but slice probably mislabeled
    """
    # Accept both canonical name AND legacy codex name (in source files before merge normalizes)
    if c.get("slice") not in ("same_gender_similar", "same_gender_similar_voice"):
        return 0
    # Normalize legacy slice name in source file too
    if c.get("slice") == "same_gender_similar_voice":
        c["slice"] = "same_gender_similar"
    parts = c.get("participants", {})
    agent = parts.get("agent", {})
    customer = parts.get("customer", {})
    a_gender = agent.get("gender")
    c_gender = customer.get("gender")
    a_voice = agent.get("voice_id")
    c_voice = customer.get("voice_id")

    fixed = 0

    # Case 1: both F + identical voice — assign different female voices
    if a_gender == "F" and c_gender == "F":
        if a_voice == c_voice:
            agent["voice_id"] = "zh-TW-HsiaoChenNeural"
            agent["voice_pool"] = "azure_zh_tw_female"
            customer["voice_id"] = "zh-TW-HsiaoYuNeural"
            customer["voice_pool"] = "azure_zh_tw_female_alt1"
            fixed = 1
        return fixed

    # Case 2: both M — convert to F+F (only 1 male voice available)
    if a_gender == "M" and c_gender == "M":
        agent["gender"] = "F"
        agent["voice_id"] = "zh-TW-HsiaoChenNeural"
        agent["voice_pool"] = "azure_zh_tw_female"
        customer["gender"] = "F"
        customer["voice_id"] = "zh-TW-HsiaoYuNeural"
        customer["voice_pool"] = "azure_zh_tw_female_alt1"
        # Note in metadata
        c.setdefault("metadata", {})["voice_remap_note"] = "Converted M+M → F+F due to single zh-TW male voice in Azure budget"
        return 1

    # Case 3: mixed gender — slice is mislabeled, but keep voices distinct
    if a_voice == c_voice:
        # Pick different voices
        if a_gender == "F":
            agent["voice_id"] = "zh-TW-HsiaoChenNeural"
            agent["voice_pool"] = "azure_zh_tw_female"
            customer["voice_id"] = "zh-TW-HsiaoYuNeural"
            customer["voice_pool"] = "azure_zh_tw_female_alt1"
            customer["gender"] = "F"  # force same-gender
        else:
            agent["voice_id"] = "zh-TW-HsiaoChenNeural"
            agent["voice_pool"] = "azure_zh_tw_female"
            customer["voice_id"] = "zh-TW-HsiaoYuNeural"
            customer["voice_pool"] = "azure_zh_tw_female_alt1"
            agent["gender"] = "F"
            customer["gender"] = "F"
        c.setdefault("metadata", {})["voice_remap_note"] = "Mismatched gender, forced to F+F with distinct voice IDs"
        return 1
    return 0


def recalibrate_role_signal(c):
    """Apply heuristic to set role_signal_strength.

    strong: recording_start=full_call AND (greeting OR service_script OR verification_request tag in any turn)
    medium: recording_start=mid_call but agent still uses process_explanation/verification_request/agent_support
    weak: mid_call AND same_gender_similar slice AND minimal canonical agent tags
    """
    rs = c.get("recording_start", "full_call")
    slice_name = c.get("slice")
    all_tags = set()
    for t in c.get("turns", []):
        all_tags.update(t.get("tags", []))

    strong_cues = {"greeting", "service_script", "verification_request"}
    medium_cues = {"process_explanation", "verification_request", "agent_support", "hold_prompt"}

    # Determine signal level
    if rs == "full_call" and (strong_cues & all_tags):
        new_sig = "strong"
    elif rs == "mid_call" and slice_name == "same_gender_similar":
        new_sig = "weak"
    elif rs == "mid_call" and (medium_cues & all_tags):
        new_sig = "medium"
    elif rs == "mid_call":
        new_sig = "weak"
    else:
        new_sig = "medium"  # fallback

    old_sig = c.get("role_signal_strength")
    if old_sig != new_sig:
        c["role_signal_strength"] = new_sig
        return 1
    return 0


def cleanup_file(path: pathlib.Path):
    """Apply all cleanup steps to one file in-place."""
    try:
        cases = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        # Try to recover from trailing garbage (the Agent 3 issue)
        text = path.read_text(encoding="utf-8")
        # Find last `]` and truncate after it
        last_bracket = text.rfind("]")
        if last_bracket > 0:
            text = text[:last_bracket + 1]
            try:
                cases = json.loads(text)
                path.write_text(text, encoding="utf-8")
                print(f"  ! Recovered {path.name} from trailing garbage")
            except json.JSONDecodeError:
                print(f"  ✗ {path.name}: cannot recover from {e}")
                return None
        else:
            print(f"  ✗ {path.name}: {e}")
            return None

    stats = {
        "turn_idx": 0, "voice_pool": 0, "tags": 0,
        "smk003": 0, "cs_011": 0, "same_gender": 0, "role_sig": 0,
    }

    for c in cases:
        stats["turn_idx"]   += fix_turn_idx(c)
        stats["voice_pool"] += fix_voice_pool(c)
        stats["tags"]       += add_canonical_tags(c)
        stats["smk003"]     += fix_long_gap_pauses(c)
        stats["cs_011"]     += fix_cs_011_language(c)
        stats["same_gender"]+= fix_same_gender_similar(c)
        stats["role_sig"]   += recalibrate_role_signal(c)

    path.write_text(json.dumps(cases, ensure_ascii=False, indent=2), encoding="utf-8")
    return stats


def main():
    print(f"Cleaning {len(SOURCES)} source files in {SPECS_DIR}\n")
    total = {k: 0 for k in ["turn_idx", "voice_pool", "tags", "smk003", "cs_011", "same_gender", "role_sig"]}
    for name in SOURCES:
        path = SPECS_DIR / name
        if not path.exists():
            print(f"  - {name}: missing, skip")
            continue
        stats = cleanup_file(path)
        if stats is None:
            continue
        print(f"  ✓ {name:30}  +turn_idx={stats['turn_idx']:>4}  +tags={stats['tags']:>3}  voice_pool={stats['voice_pool']:>2}  same_gender={stats['same_gender']:>2}  role_sig_chg={stats['role_sig']:>3}")
        for k, v in stats.items():
            total[k] += v

    print()
    print("=== Totals ===")
    print(f"  turn_idx added:       {total['turn_idx']}")
    print(f"  voice_pool normalized:{total['voice_pool']}")
    print(f"  canonical tags added: {total['tags']}")
    print(f"  v2_smk003 long-gap:   {total['smk003']}")
    print(f"  cs_011 lang fixed:    {total['cs_011']} turns")
    print(f"  same_gender_similar:  {total['same_gender']}")
    print(f"  role_signal changed:  {total['role_sig']}")
    print()
    print("Next: rerun scripts/merge_dialog_specs.py + validate against schema.")


if __name__ == "__main__":
    main()
